Fix BLS support for sequence models
triton-inference-server/python_backend pull request #115
Opened 2022-01-19 16:57 UTC by Tabrizian

Fix the support for sequence models in BLS. New `sequence_start` and `sequence_end` flags have been added to indicate the starting and ending of sequences in BLS requests. An example BLS request for sequence models:

```python
 infer_request = pb_utils.InferenceRequest(
            model_name='onnx_nobatch_sequence_int32',
            inputs=[input],
            requested_output_names=['OUTPUT'],
            sequence_start=True,
            sequence_end=False,
            correlation_id=correlation_id)
```

Testing in the server PR:

https://github.com/triton-inference-server/server/pull/3826

2022-01-19 17:14 UTC, deadeyegoodwin requested changes

2022-01-19 17:14 UTC, deadeyegoodwin commented on src/infer_request.cc
> +InferRequest::SequenceStart()
Existing Triton code just uses Flags(), so it would be good to continue that pattern. See sequence_batcher for example.

2022-01-20 17:21 UTC, deadeyegoodwin approved these changes

2022-01-20 21:33 UTC, tanmayv25 approved these changes

2022-01-21 18:40 UTC, merged