Add a note about Python GIL
triton-inference-server/python_backend pull request #124
Opened 2022-03-07 22:58 UTC by Tabrizian

2022-03-07 23:23 UTC, tanmayv25 commented on README.md
> +## Python Global Interpreter Lock (GIL)
"Multiple Model Instance Support"?
Then we can talk about how GIL prevents us from attaining concurrency in single python process.

2022-03-07 23:59 UTC, CoderHam requested changes

2022-03-07 23:59 UTC, CoderHam commented on README.md
> +to work around this issue, Python backend spawns a complete separate process for each
Remove complete. Python backend spawns a separate process

2022-03-07 23:59 UTC, CoderHam commented on README.md
> +[Tensorflow](https://github.com/triton-inference-server/tensorflow_backend), and
TensorFlow

2022-03-07 23:59 UTC, CoderHam commented on README.md
> +an additional thread instead of spawning a separate process.
create additional threads instead of spawning separate processes.

2022-03-08 15:52 UTC, CoderHam approved these changes

2022-03-08 17:11 UTC, tanmayv25 approved these changes

2022-03-08 17:21 UTC, merged